#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extention or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

textype() { \
	command="pdflatex"
	grep -i xunicode "$file" > /dev/null && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	grep -i natbib "$file" || grep -i biblatex "$file" || grep -i apacite "$file" > /dev/null &&
	bibtex "$bases" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	}

mdown(){
        command="pandoc "$file" -o "$base".pdf -V geometry:margin=1in --pdf-engine=xelatex "
        #( sed 15q "$file" | grep -i -q 'beamer' ) && command="pandoc "$file" -o "$base".pdf --pdf-engine=xelatex -t beamer"
        grep -i beamer "$file" > /dev/null && command="pandoc "$file" -o "$base".pdf --pdf-engine=xelatex -t beamer --filter pandoc-citeproc"
	#sed 15q "$file" | grep -i -q 'beamer' ) && command="pandoc "$file" -o "$base".pdf -V geometry:margin=1in -V fontsize=12px --latex-engine=xelatex -t beamer"
        $command
}

case "$ext" in
	# Try to keep these cases in alphabetical order.
	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
	c) cc "$file" -o "$base" && "$base" ;;
	cpp) g++ "$file" -o "$base" && "$base" ;;
	cs) mcs "$file" && mono "$base".exe ;;
	go) go run "$file" ;;
	h) sudo make install ;;
	java) javac -d classes "$file" && java -cp classes "${1%.*}" ;;
	m) octave "$file" ;;
	#md)	if  [ -x "$(command -v lowdown)" ]; then
	#		lowdown -d nointem -e super "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
	#	elif [ -x "$(command -v groffdown)" ]; then
	#		groffdown -i "$file" | groff -T pdf > "$base.pdf"
	#	else
	#		pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file"
	#	fi ; ;;
	md) mdown "$file" ;;
	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
	ms) preconv "$file" | refer -PS -e | groff -me -ms -kept -T pdf > "$base".pdf ;;
	org) emacs "$file" --batch -u "$USER" -f org-latex-export-to-pdf ;;
	py) python "$file" ;;
	[rR]md) Rscript -e "rmarkdown::render('$file', quiet=TRUE)" ;;
	rs) cargo build ;;
	sass) sassc -a "$file" "$base.css" ;;
	scad) openscad -o "$base".stl "$file" ;;
	sent) setsid -f sent "$file" 2>/dev/null ;;
	tex) textype "$file" ;;
	*) head -n1 "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
